import React from 'react'
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import "../../css/projects.css"
import image1 from "../../images/workIt.png"
import image2 from "../../images/leaderBoard.png"
import image3 from "../../images/0.png"
import image4 from "../../images/1.png"
import image5 from "../../images/10.png"
import image6 from "../../images/2.png"
import image7 from "../../images/5.png"
import image8 from "../../images/6.png"

const Projects = () => {
  return (
    <div className="container">
        <Navbar/>
        <section className="projects" id="projects">
        <div className="container-project">
            <hr size="3" color="#00b7ff"/>
            <br/>
            <div className="title">
                <h3>Featured Projects -</h3>
                <h3>Projects are live hosted!</h3>
                <a href="https://github.com/Lokeshburade007" target="_blank" className="btn" rel="noreferrer">View
                    All</a>
            </div>
            <hr size="3" color="#00b7ff"/>
            <br/>
            <div className="projects-wrapper">
                <div className="project">
                    <div className="img-container">
                        <a href="https://github.com/Lokeshburade007/WorkIT.git" target="_blank" rel="noreferrer">
                            <img src={image1} alt="Project 1 : WorkIt Software Ecommerce Application" />
                        </a>
                    </div>
                    <div className="description">
                        <h4>Project 1 : WorkIt Software Ecommerce Application</h4>
                        <div className="links">
                            <a href="https://github.com/Lokeshburade007/WorkIT.git" target="_blank"
                                rel="noreferrer">
                                <i className="fab fa-github"></i>
                            </a>
                            <a href="https://github.com/Lokeshburade007/WorkIT.git" target="_blank" rel="noreferrer">
                                <i className="fa fa-globe"></i> 
                            </a>
                        </div>
                    </div>
                    <p>This is a Software based Ecommerce Web Application to a Lead for Company. <br/> <b style={{color: "#00abf0"}}>Tech Stack:- </b>ReactJS, NodeJs, ExpressJS, TailwindCSS, Firebase, Figma.
                    </p>
                    <p><b style={{color: "#00abf0"}}>Explaination:- </b>Basically this is lead generation Application for TWJ IT SOLUTION. Employees will be used this Application to generate a lead from Clients for their company. Reward list is also given here.
                    </p>
                </div>
                <div className="project">
                    <div className="img-container">
                        <a href="https://github.com/Lokeshburade007/LeaderBoard.git" target="_blank" rel="noreferrer">
                            <img src={image2} alt="Project 2 : LeaderBoard Andriod Application" />
                        </a>
                    </div>
                    <div className="description">
                        <h4>Project 2 : LeaderBoard Andriod Application</h4>
                        <div className="links">
                            <a href="https://github.com/Lokeshburade007/LeaderBoard.git" target="_blank"
                                rel="noreferrer">
                                <i className="fab fa-github"></i>
                            </a>
                            <a href="https://github.com/Lokeshburade007/LeaderBoard.git" target="_blank" rel="noreferrer">
                                <i className="fa fa-globe"></i>
                            </a>
                        </div>
                    </div>
                    <p>This is a Android Application to See the LeaderBoard By the Ranking based on reward System. <br/> <b style={{color: "#00abf0"}}>Tech Stack:- </b>Flutter, Dart, AndroidStudio, Firebase, Figma.
                    </p>
                    <p><b style={{color: "#00abf0"}}>Explaination:- </b>This App will be used by the Employees of TWJ IT SOLUTION to see the LeaderBoard. LeaderBoard is all about the number of lead is generated by the Employees in a week or in a month or in a year.
                    </p>
                </div>

                <div className="project">
                    <div className="img-container">
                        <a href="https://missing-people-identification.onrender.com/" target="_blank" rel="noreferrer">
                            <img src={image3} alt="Projects 3 : Missing People Identification System using Deep learning" />
                        </a>
                    </div>
                    <div className="description">
                        <h4>Project 3 : Missing People Identification System using Deep learning</h4>
                        <div className="links">
                            <a href="https://github.com/Lokeshburade007/missing-people-identification.git" target="_blank"
                                rel="noreferrer">
                                <i className="fab fa-github"></i>
                            </a>
                            <a href="https://missing-people-identification.onrender.com/" target="_blank" rel="noreferrer">
                                <i className="fa fa-globe"></i>
                            </a>
                        </div>
                    </div>
                    <p>This is a Our Final year Btech Project. <br/> <b style={{color: "#00abf0"}}>Tech Stack:- </b>NodeJs, ExpressJS, EJS, TailwindCSS, FaceApi, Deeplearning Models, Twilio And MongoDB.
                    </p>
                    <p><b style={{color: "#00abf0"}}>Explaination:- </b> Whenever a missing person complaint is registered with any police station, it is automatically entered into our database. If someone finds that missing person anywhere, they can search for them using our missing people identification web application and directly inform the nearest police station with a single click within the application.
                    </p>
                </div>
                <div className="project">
                    <div className="img-container">
                        <a href="https://fanciful-swan-db72de.netlify.app" target="_blank" rel="noreferrer">
                            <img src={image4} alt="Projects 4 : FlipKart Clone" />
                        </a>
                    </div>
                    <div className="description">
                        <h4>Project 4 : FlipKart Clone</h4>
                        <div className="links">
                            <a href="https://github.com/Lokeshburade007/Frontend-CSS-Project.git" target="_blank"
                                rel="noreferrer">
                                <i className="fab fa-github"></i>
                            </a>
                            <a href="https://fanciful-swan-db72de.netlify.app" target="_blank" rel="noreferrer">
                                <i className="fa fa-globe"></i>
                            </a>
                        </div>
                    </div>
                    <p><b style={{color: "#00abf0"}}>Explaination:- </b>This is a Flipkart Clone UI Design. I was started my journy towards web-development from this mini project.
                        <br/> <b style={{color: "#00abf0"}}>Tech Stack:- </b>Using HTML,CSS , JS & Boostrap
                    </p>
                </div>
                <div className="project">
                    <div className="img-container">
                        <a href="https://shreekrushananagari.github.io/" target="_blank" rel="noreferrer">
                            <img src={image5} alt="Project 5 : Realtime freelancing Website" />
                        </a>
                    </div>
                    <div className="description">
                        <h4>Project 5 : Realtime freelancing Website
                        </h4>
                        <div className="links">
                            <a href="https://shreekrushananagari.github.io/" target="_blank"
                                rel="noreferrer">
                                <i className="fab fa-github"></i>
                            </a>
                            <a href="https://shreekrushananagari.github.io/" target="_blank" rel="noreferrer">
                                <i className="fa fa-globe"></i>
                            </a>
                        </div>
                    </div>
                    <p><b style={{color: "#00abf0"}}>Explaination:- </b>Shree Krushana Nagari , This is a Static realtime Website for layout Seller. I worked as a freelancer
                        <br/> <b style={{color: "#00abf0"}}>Tech Stack:- </b>Using HTML, Tailwind CSS & JS
                    </p>
                </div>

                <div className="project">
                    <div className="img-container">
                        <a href="https://krupasindhuseva.org/" target="_blank" rel="noreferrer">
                            <img src={image6} alt="Projects 6 : Realtime Project" />
                        </a>
                    </div>
                    <div className="description">
                        <h4>Project 6 : Realtime NGO Website</h4>
                        <div className="links">
                            <a href="https://github.com/Lokeshburade007/krupasindhuNGO.git" target="_blank"
                                rel="noreferrer">
                                <i className="fab fa-github"></i>
                            </a>
                            <a href='https://krupasindhuseva.org/' target="_blank" rel="noreferrer">
                                <i className="fa fa-globe"></i>
                            </a>
                        </div>
                    </div>
                    <p><b style={{color: "#00abf0"}}>Explaination:- </b>This is a Static realtime Website for Krupa sindhu seva. It is a Realtime NGO, I worked as a freelancer
                        <br/> <b style={{color: "#00abf0"}}>Tech Stack:- </b>Using HTML, Tailwind CSS & JS
                    </p>
                </div>

                <div className="project">
                    <div className="img-container">
                        <a href="https://my-personal-library-bookset.netlify.app/" target="_blank" rel="noreferrer">
                            <img src={image7} alt="Projects 7 : UI Design Using Tailwind CSS" />
                        </a>
                    </div>
                    <div className="description">
                        <h4>Project 7 : UI Design Using Tailwind</h4>
                        <div className="links">
                            <a href="https://github.com/Lokeshburade007/My-Personal-Library.git" target="_blank"
                                rel="noreferrer">
                                <i className="fab fa-github"></i>
                            </a>
                            <a href="https://my-personal-library-bookset.netlify.app/" target="_blank" rel="noreferrer">
                                <i className="fa fa-globe"></i>
                            </a>
                        </div>
                    </div>
                    <p><b style={{color: "#00abf0"}}>Explaination:- </b>Using TailwindCSS, I was created this My personal Library UI design. I was created this mini project within 1 hour only!!</p>
                </div>

                <div className="project">
                    <div className="img-container">
                        <a href="https://github.com/Lokeshburade007/Crackit_Academy.git" target="_blank" rel="noreferrer">
                            <img src={image8} alt="Projects 8 : Gate Learnning Platform (using PHP)"/>
                        </a>
                    </div>
                    <div className="description">
                        <h4>Project 8 : Gate Learning project</h4>
                        <div className="links">
                            <a href="https://github.com/Lokeshburade007/Crackit_Academy.git" target="_blank"
                                rel="noreferrer">
                                <i className="fab fa-github"></i>
                            </a>
                            <a href="https://github.com/Lokeshburade007/Crackit_Academy.git" target="_blank" rel="noreferrer">
                                <i className="fa fa-globe"></i>
                            </a>
                        </div>
                    </div>
                    <p><b style={{color: "#00abf0"}}>Explaination:- </b>I was created from this Scratch. In this Project, I was used pure HTML, CSS ,JS , PHP and MYSQL and also used the concept of Backend. For backend i was used PHP and Mysql for Database</p>
                </div>
            </div>
        </div>
    </section>
        <Footer/>
    </div>
  )
}

export default Projects